messages:
  ban-message: "&cYou are banned from this server!\n&cReason: &f{reason}\n&cTime left: &f{time_left}\n&cBanned by: &f{punisher}"
  mute-message: "&cYou are muted and cannot speak!\n&cReason: &f{reason}\n&cTime left: &f{time_left}\n&cMuted by: &f{punisher}"
  kick-message: "&cYou have been kicked from the server!\n&cReason: &f{reason}\n&cKicked by: &f{punisher}"
  blacklist-message: "&cYou are blacklisted from this server!\n&cReason: &f{reason}\n&cBlacklisted by: &f{punisher}"
  banip-message: "&cYour IP is banned from this server!\n&cReason: &f{reason}\n&cTime left: &f{time_left}\n&cBanned by: &f{punisher}"
  punishment-expired: "&aYour {punishment_type} has expired!"
  no-permission: "&cYou don't have permission to use this command!"
  player-not-found: "&cPlayer not found!"
  invalid-duration: "&cInvalid duration format! Use s, m, h, d, w, mo, y."
  punishment-success: "&aPunishment applied successfully!"
  punishment-removed: "&aPunishment removed successfully!"
  history-header: "&6=== Punishment History for {player} ==="
  history-entry: "&f- {date} - &c&L{action}: &f{duration}, &cReason: &f{reason}, &cBy: &f{punisher}"
  history-footer: "&6=== End of Punishment History ==="

time-format:
  year: "year"
  years: "years"
  month: "month"
  months: "months"
  week: "week"
  weeks: "weeks"
  day: "day"
  days: "days"
  hour: "hour"
  hours: "hours"
  minute: "minute"
  minutes: "minutes"
  second: "second"
  seconds: "seconds"